version: "2"
services:
  app:
    container_name: app
    restart: always
    build: FeelFood-Backend
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
  angular:
    container_name: angular
    restart: always
    build: FeelFood-Frontend
    ports:
      - "4200:4200"
#  proxy:
#    image: jwilder/nginx-proxy
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#    ports:
#      - "80:80"
#    networks:
#      - proxy
#
#networks:
#  proxy:
#    driver: bridge